// Code generated by command: go run asm.go -out sum.s -stubs sum.go. DO NOT EDIT.

#include "textflag.h"

// func SumVec(input []int64) int64
TEXT ·SumVec(SB), NOSPLIT, $0-32
	XORQ AX, AX
	MOVQ AX, ret+24(FP)
	RET
