// Code generated by command: go run asm.go -out sum.s -stubs sum.go. DO NOT EDIT.

#include "textflag.h"

// func SumVec(input []int64) int64
// Requires: AVX, AVX2
TEXT ·SumVec(SB), NOSPLIT, $0-32
	MOVQ         input_base+0(FP), AX
	MOVQ         input_len+8(FP), CX
	VMOVDQU      (AX), Y0
	MOVQ         $0x00000004, CX
	VMOVDQU      (AX)(CX*8), Y1
	VPADDQ       Y0, Y1, Y0
	VEXTRACTI128 $0x01, Y0, X1
	VPADDQ       X0, X1, X0
	VPSRLDQ      $0x08, X0, X1
	VPADDQ       X0, X1, X0
	VMOVQ        X0, AX
	MOVQ         AX, ret+24(FP)
	RET
